In [5]:
import pandas as pd
import numpy as np

In [6]:
simudata = pd.read_excel("dgima1.9.xlsx")
simudata['index'] = range(1, simudata.shape[0]+1)
simudata = simudata[['index'] + list(simudata.columns[:-1])]

simudata1 = simudata.iloc[:, :16]

In [7]:
mydata = simudata.iloc[:, 16:]
mydata['index'] = simudata['index']
mydata = mydata[['index'] + list(mydata.columns[:-1])]

categories = ["גימלאות", "SemelGimla:", "ShemGimla:", "MiTarGimla:", "AdTarGimla:", "GovaGimlaTakin:", "SchumGovaGimla:", "YemeyZakaut:", "YemeyNitzul:",
              "נכויות", "Semelnechut:", "ShemNechut:", "AchuzRefui:", "EKosher:", "MiTarNechut:", "AdTarNechut:",
              "מצב משפחתי", "SemelMazavMish:",
              "עיסוקים", "MisparIsuk:", "SemelIsuk:", "ShemIsuk:", "MaamadIsuk:", "MiTarIsuk:", "AdTarIsuk:", "HachnasaTakin:",
              "הכנסות", "MisparIsukHachnasa:", "ShemHachnasa:", "SchumHachnasa:", "MiTarHachnasa:", "AdTarHachnasa:"]

# Create an empty DataFrame with the category and subcategory names as column names
sub_cat_gim = ["SemelGimla:", "ShemGimla:", "MiTarGimla:", "AdTarGimla:", "GovaGimlaTakin:", "SchumGovaGimla:", "YemeyZakaut:", "YemeyNitzul:"]
sub_cat_nec = ["Semelnechut:", "ShemNechut:", "AchuzRefui:", "EKosher:", "MiTarNechut:", "AdTarNechut:"]
sub_cat_isu = ["MisparIsuk:", "SemelIsuk:", "ShemIsuk:", "MaamadIsuk:", "MiTarIsuk:", "AdTarIsuk:", "HachnasaTakin:"]
sub_cat_hac = ["MisparIsukHachnasa:", "ShemHachnasa:", "SchumHachnasa:", "MiTarHachnasa:", "AdTarHachnasa:"]
sub_cat_maz = ["SemelMazavMish:"]

count_matrix = pd.DataFrame(0, index=range(mydata.shape[0]), columns=categories)
indices = pd.DataFrame(index=range(mydata.shape[0]), columns=categories)

In [8]:

# Convert the columns of mydata to string type if needed
mydata = mydata.astype(str)

# Initialize indices and count_matrix with zeros
indices = pd.DataFrame(0, index=range(mydata.shape[0]), columns=categories)
count_matrix = pd.DataFrame(0, index=range(mydata.shape[0]), columns=categories)

# Loop through each category
for j, category in enumerate(categories):
    # Find the column indices that contain the current category in each row
    row_indices = np.char.find(mydata.values, category) != -1

    # Store the row indices where the category is found
    indices[category] = ';'.join(map(str, np.where(row_indices)[0]))

    # Count the occurrences of the category in each row
    count_matrix[category] = row_indices.sum(axis=1)

TypeError: string operation on non-string array

In [4]:
# # Convert the columns of mydata to string type if needed
# mydata = mydata.astype(str)

# # Initialize the indices and count_matrix with the appropriate dimensions
# indices = pd.DataFrame(index=range(mydata.shape[0]), columns=categories)
# count_matrix = pd.DataFrame(0, index=range(mydata.shape[0]), columns=categories)

# # Loop through each row of the data
# for i in range(mydata.shape[0]):
#     # Loop through each category
#     for j in range(len(categories)):
#         # Find the column indices that contain the current category in this row
#         row_indices = np.where(np.char.find(mydata.iloc[i, :].values.astype(str), categories[j]) != -1)[0]
        
#         # If there are any such column indices, store the indices in the "indices" matrix
#         if len(row_indices) > 0:
#             indices.at[i, categories[j]] = ";".join(map(str, row_indices))  # Store indices as a string with ";" as a separator
#             count = len(row_indices)
#             count_matrix.at[i, categories[j]] = count

# # Set the column names of indices
# indices.columns = categories

KeyboardInterrupt:

In [ ]:
count_gim = 0
count_nech = 0
count_maz = 0
count_isuk = 0
count_hach = 0

for i in range(mydata.shape[0]):
    if count_matrix.iloc[i, 1] > count_gim:
        count_gim = count_matrix.iloc[i, 1]
    if count_matrix.iloc[i, 10] > count_nech:
        count_nech = count_matrix.iloc[i, 10]
    if count_matrix.iloc[i, 17] > count_maz:
        count_maz = count_matrix.iloc[i, 17]
    if count_matrix.iloc[i, 19] > count_isuk:
        count_isuk = count_matrix.iloc[i, 19]
    if count_matrix.iloc[i, 27] > count_hach:
        count_hach = count_matrix.iloc[i, 27]

In [ ]:
simudata1["גימלאות"] = np.nan
# Create a matrix of NaNs to hold the new columns
new_cols = np.empty((mydata.shape[0], count_gim * len(sub_cat_gim)))
new_cols[:] = np.nan
# Loop over the categories and create the new column names
col_names = []
for i in range(1, count_gim + 1):
    for j in range(len(sub_cat_gim)):
        col_names.append(sub_cat_gim[j] + "_" + str(i))
# Add the new columns to the data frame
simudata1 = pd.concat([simudata1, pd.DataFrame(new_cols, columns=col_names)], axis=1)


simudata1["נכויות"] = np.nan
# Create a matrix of NaNs to hold the new columns
new_cols = np.empty((mydata.shape[0], count_nech * len(sub_cat_nec)))
new_cols[:] = np.nan
# Loop over the categories and create the new column names
col_names = []
for i in range(1, count_nech + 1):
    for j in range(len(sub_cat_nec)):
        col_names.append(sub_cat_nec[j] + "_" + str(i))
# Add the new columns to the data frame
simudata1 = pd.concat([simudata1, pd.DataFrame(new_cols, columns=col_names)], axis=1)


simudata1["מצב משפחתי"] = np.nan
# Create a matrix of NaNs to hold the new columns
new_cols = np.empty((mydata.shape[0], count_maz * len(sub_cat_maz)))
new_cols[:] = np.nan
# Loop over the categories and create the new column names
col_names = []
for i in range(1, count_maz + 1):
    for j in range(len(sub_cat_maz)):
        col_names.append(sub_cat_maz[j] + "_" + str(i))
# Add the new columns to the data frame
simudata1 = pd.concat([simudata1, pd.DataFrame(new_cols, columns=col_names)], axis=1)


simudata1["עיסוקים"] = np.nan
# Create a matrix of NaNs to hold the new columns
new_cols = np.empty((mydata.shape[0], count_isuk * len(sub_cat_isu)))
new_cols[:] = np.nan
# Loop over the categories and create the new column names
col_names = []
for i in range(1, count_isuk + 1):
    for j in range(len(sub_cat_isu)):
        col_names.append(sub_cat_isu[j] + "_" + str(i))
# Add the new columns to the data frame
simudata1 = pd.concat([simudata1, pd.DataFrame(new_cols, columns=col_names)], axis=1)


simudata1["הכנסות"] = np.nan
# Create a matrix of NaNs to hold the new columns
new_cols = np.empty((mydata.shape[0], count_hach * len(sub_cat_hac)))
new_cols[:] = np.nan
# Loop over the categories and create the new column names
col_names = []
for i in range(1, count_hach + 1):
    for j in range(len(sub_cat_hac)):
        col_names.append(sub_cat_hac[j] + "_" + str(i))
# Add the new columns to the data frame
simudata1 = pd.concat([simudata1, pd.DataFrame(new_cols, columns=col_names)], axis=1)

In [ ]:
# Add the new columns to the data frame
simudata1 = pd.concat([simudata1, pd.DataFrame(new_cols, columns=col_names)], axis=1)
simudata1.columns = list(simudata1.columns[:simudata1.shape[1]-new_cols.shape[1]]) + col_names

# Select columns 1, 17, and the remaining columns of simudata1
simulation_data = simudata1.iloc[:, np.r_[0, 16:simudata1.shape[1]]]

# Create copies of mydata and simulation_data
test_mydata = mydata.copy()
test_simulationdata = simulation_data.copy()

In [ ]:
# Initialize count for each sub_cat_gim term to 0
sub_cat_gim_count = [0] * len(sub_cat_gim)

# Iterate over rows of test_mydata
for i in range(test_mydata.shape[0]):
    # Iterate over columns of test_mydata
    for j in range(test_mydata.shape[1]):
        if test_mydata.iloc[i, j] in sub_cat_gim:
            col_index = sub_cat_gim.index(test_mydata.iloc[i, j])
            if sub_cat_gim_count[col_index] < count_gim:
                sub_cat_gim_count[col_index] += 1
                test_mydata.iloc[i, j] = f"{test_mydata.iloc[i, j]}_{sub_cat_gim_count[col_index]}"

# Initialize count for each sub_cat_nec term to 0
sub_cat_nec_count = [0] * len(sub_cat_nec)

# Iterate over rows of test_mydata
for i in range(test_mydata.shape[0]):
    # Iterate over columns of test_mydata
    for j in range(test_mydata.shape[1]):
        if test_mydata.iloc[i, j] in sub_cat_nec:
            col_index1 = sub_cat_nec.index(test_mydata.iloc[i, j])
            if sub_cat_nec_count[col_index1] < count_nech:
                sub_cat_nec_count[col_index1] += 1
                test_mydata.iloc[i, j] = f"{test_mydata.iloc[i, j]}_{sub_cat_nec_count[col_index1]}"

# Initialize count for each sub_cat_isu term to 0
sub_cat_isu_count = [0] * len(sub_cat_isu)

# Iterate over rows of test_mydata
for i in range(test_mydata.shape[0]):
    # Iterate over columns of test_mydata
    for j in range(test_mydata.shape[1]):
        if test_mydata.iloc[i, j] in sub_cat_isu:
            col_index2 = sub_cat_isu.index(test_mydata.iloc[i, j])
            if sub_cat_isu_count[col_index2] < count_isuk:
                sub_cat_isu_count[col_index2] += 1
                test_mydata.iloc[i, j] = f"{test_mydata.iloc[i, j]}_{sub_cat_isu_count[col_index2]}"

# Initialize count for each sub_cat_hac term to 0
sub_cat_hach_count = [0] * len(sub_cat_hac)

# Iterate over rows of test_mydata
for i in range(test_mydata.shape[0]):
    # Iterate over columns of test_mydata
    for j in range(test_mydata.shape[1]):
        if test_mydata.iloc[i, j] in sub_cat_hac:
            col_index3 = sub_cat_hac.index(test_mydata.iloc[i, j])
            if sub_cat_hach_count[col_index3] < count_hach:
                sub_cat_hach_count[col_index3] += 1
                test_mydata.iloc[i, j] = f"{test_mydata.iloc[i, j]}_{sub_cat_hach_count[col_index3]}"

# Initialize count for each sub_cat_maz term to 0
sub_cat_maz_count = [0] * len(sub_cat_maz)

# Iterate over rows of test_mydata
for i in range(test_mydata.shape[0]):
    # Iterate over columns of test_mydata
    for j in range(test_mydata.shape[1]):
        if test_mydata.iloc[i, j] in sub_cat_maz:
            col_index4 = sub_cat_maz.index(test_mydata.iloc[i, j])
            if sub_cat_maz_count[col_index4] < count_maz:
                sub_cat_maz_count[col_index4] += 1
                test_mydata.iloc[i, j] = f"{test_mydata.iloc[i, j]}_{sub_cat_maz_count[col_index4]}"

In [ ]:
import pandas as pd

# Write test_mydata to Excel
# test_mydata.to_excel("C:/Users/SaarP/Box/צוות תעסוקה/יעוץ לממונה תעסוקה/מעונות יום/פרויקט העברת מידע- תקשוב ממשל זמין/טיוב - R/test_mydata.xlsx", index=False)

# # Write test_simulationdata to Excel
# test_simulationdata.to_excel("C:/Users/SaarP/Box/צוות תעסוקה/יעוץ לממונה תעסוקה/מעונות יום/פרויקט העברת מידע- תקשוב ממשל זמין/טיוב - R/test_simulationdata.xlsx", index=False)

# # Read test_simulationdata_final.csv
# simulation = pd.read_csv("C:/Users/SaarP/Box/צוות תעסוקה/יעוץ לממונה תעסוקה/מעונות יום/פרויקט העברת מידע- תקשוב ממשל זמין/טיוב - R/test_simulationdata_final.csv")

# Select columns from simudata and simulation
info = simudata.iloc[:, 0:16]
simul = simulation.iloc[:, 1:]

# Merge info and simul data frames
merged_data = info.merge(simul, on="index")

# Write merged_data to Excel
merged_data.to_excel("C:/Users/SaarP/Box/צוות תעסוקה/יעוץ לממונה תעסוקה/מעונות יום/פרויקט העברת מידע- תקשוב ממשל זמין/טיוב - R/final_data.xlsx", index=False)

## Dates converter from 01011995 to 01/01/1995 00:00

In [ ]:
import pandas as pd

# Subset the first 100 rows of mydata and assign it to test_mydata
test_mydata = mydata.head(100)

# Check the class of the column "תאריך הגשה 1"
print(type(mydata["תאריך הגשה 1"][0]))

# Iterate over the columns and rows of test_mydata
for i in range(test_mydata.shape[1]):
    for j in range(test_mydata.shape[0]):
        # Check if the cell is an 8-digit number starting with "2"
        if str(test_mydata.iloc[j, i]).isdigit() and len(str(test_mydata.iloc[j, i])) == 8 and str(test_mydata.iloc[j, i]).startswith("2"):
            # Convert the cell to character type
            test_mydata.iloc[j, i] = str(test_mydata.iloc[j, i])
            # Convert the string to yyyy/mm/dd format
            test_mydata.iloc[j, i] = "/".join([test_mydata.iloc[j, i][:4], test_mydata.iloc[j, i][4:6], test_mydata.iloc[j, i][6:8]])

# Check the updated test_mydata
print(test_mydata)

In [25]:
test_mydata = pd.read_excel("C:/Users/SaarP/Box/צוות תעסוקה/יעוץ לממונה תעסוקה/מעונות יום/פרויקט העברת מידע- תקשוב ממשל זמין/טיוב - R/test_mydata.xlsx")
test_simulationdata = pd.read_excel("C:/Users/SaarP/Box/צוות תעסוקה/יעוץ לממונה תעסוקה/מעונות יום/פרויקט העברת מידע- תקשוב ממשל זמין/טיוב - R/test_simulationdata.xlsx")

In [26]:
keysList = test_simulationdata.columns.values.tolist()

In [27]:
for index, row in test_mydata.iterrows():

    d = row.to_dict().values()
    myL = list(d)
    
    uid = myL[0]
    
    i = -2
    
    while i < len(myL)-2:
        i = i + 2

        # print(i)
        key = myL[i- 1]
        value = myL[i]
        
        if value in keysList:
            #print('replace ->>>>>>>>',value)
            i = i + 1
            key = myL[i - 1]
            value = myL[i]
            #print('to ->>>>>>>>',key, 'value', value)
            
            
        if type(key) == float:
            #print('skipp this ->>>>>', key)
            continue
            
        
        if key in keysList:
            test_simulationdata.loc[test_simulationdata["index"] == uid, key] = value
        else:
            print(uid, key)#,'->', value)

2275 T
2281 T
2371 T
2396 T
2497 T
2783 T
2866 T
2888 T
3007 T
3008 T
3072 T
3104 T
3118 T
3232 T
3474 T
3724 T
3852 T
4361 T
4605 T
5035 T
6792 T
6793 T
7033 T
7634 T
7635 T
7760 T
7761 T
7878 T
7879 T
10342 T
10343 T
12350 T
13187 T
13251 T
13252 T
13257 T
13258 T
13478 T
13606 T
13676 T
13914 T
14027 T
14028 T
14775 T
16401 T
16476 T
16477 T

In [28]:
test_simulationdata

,index,גימלאות,SemelGimla:_1,ShemGimla:_1,MiTarGimla:_1,AdTarGimla:_1,GovaGimlaTakin:_1,SchumGovaGimla:_1,YemeyZakaut:_1,YemeyNitzul:_1,...,MisparIsukHachnasa:_4,ShemHachnasa:_4,SchumHachnasa:_4,MiTarHachnasa:_4,AdTarHachnasa:_4,MisparIsukHachnasa:_5,ShemHachnasa:_5,SchumHachnasa:_5,MiTarHachnasa:_5,AdTarHachnasa:_5
0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2,גהה,הבטחת הכנסה,20210901,20211031.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18066,18067,1,גאב,אבטלה,20210611,20210903.0,NaN,21855,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18067,18068,1,גדל,דמי לידה,20210701,20211013.0,NaN,10496,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18068,18069,1,גדל,דמי לידה,20210701,20211013.0,NaN,10496,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18069,18070,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18070,18071,1,גאב,אבטלה,20210824,20210903.0,NaN,6213,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
np.NaN

In [ ]:
keysList

In [29]:
test_simulationdata.to_csv("C:/Users/SaarP/Box/צוות תעסוקה/יעוץ לממונה תעסוקה/מעונות יום/פרויקט העברת מידע- תקשוב ממשל זמין/טיוב - R/test_simulationdata_final.csv")